import { readFile } from "node:fs/promises";

/**
 * Parses a SUMO net.xml file (as generated by netconvert for this project)
 * into a typed network catalog.
 *
 * The net.xml is machine-generated with a stable structure, so a targeted
 * tag-level parser is sufficient and dependency-free. It must be re-run
 * whenever the network is rebuilt (npm run build:network).
 */

export interface NetworkPoint {
  x: number;
  y: number;
}

export interface NetworkLane {
  id: string;
  index: number;
  speedMps: number;
  lengthM: number;
  shape: NetworkPoint[];
}

/** A directed SUMO edge ("normal" function) between two junctions. */
export interface NetworkSegment {
  id: string;
  fromJunction: string;
  toJunction: string;
  lanes: NetworkLane[];
}

export interface NetworkJunction {
  id: string;
  kind: string;
  x: number;
  y: number;
  incLanes: string[];
}

export interface NetworkSignalPhase {
  index: number;
  durationS: number;
  state: string;
}

export interface NetworkSignal {
  id: string;
  programId: string;
  type: string;
  phases: NetworkSignalPhase[];
}

/** An undirected road between two adjacent junctions. */
export interface NetworkRoad {
  id: string;
  fromJunction: string;
  toJunction: string;
  segmentIds: string[];
}

export interface NetworkCatalog {
  junctions: NetworkJunction[];
  segments: NetworkSegment[];
  roads: NetworkRoad[];
  signals: NetworkSignal[];
  /** True when the network carries a geo-reference (projParameter != "!"). */
  geoReferenced: boolean;
}

interface TagInfo {
  name: string;
  attrs: Record<string, string>;
  selfClosing: boolean;
}

const TAG_PATTERN = /<(\/?)([\w:-]+)((?:\s+[\w:-]+\s*=\s*"[^"]*")*)\s*(\/?)>/g;
const ATTR_PATTERN = /([\w:-]+)\s*=\s*"([^"]*)"/g;

function parseAttrs(raw: string): Record<string, string> {
  const attrs: Record<string, string> = {};
  for (const match of raw.matchAll(ATTR_PATTERN)) {
    attrs[match[1]!] = match[2]!;
  }
  return attrs;
}

function parseShape(shape: string): NetworkPoint[] {
  if (shape.trim() === "") return [];
  return shape
    .trim()
    .split(/\s+/)
    .map((pair) => {
      const parts = pair.split(",");
      const x = Number(parts[0]);
      const y = Number(parts[1]);
      if (!Number.isFinite(x) || !Number.isFinite(y)) {
        throw new Error(`Malformed shape coordinate "${pair}" in network file`);
      }
      return { x, y };
    });
}

export async function loadNetworkCatalog(netXmlPath: string): Promise<NetworkCatalog> {
  const xml = await readFile(netXmlPath, "utf8");

  const junctions: NetworkJunction[] = [];
  const segments: NetworkSegment[] = [];
  const signals: NetworkSignal[] = [];
  let geoReferenced = false;
  let netOffset: { dx: number; dy: number } | null = null;

  let currentSignal: NetworkSignal | null = null;
  let currentEdge: NetworkSegment | null = null;
  let match: RegExpExecArray | null;

  TAG_PATTERN.lastIndex = 0;
  while ((match = TAG_PATTERN.exec(xml)) !== null) {
    const [, closing, name, rawAttrs, selfClosing] = match as unknown as [
      string, string, string, string, string,
    ];
    if (closing === "/") {
      if (name === "tlLogic" && currentSignal !== null) {
        currentSignal = null;
      }
      if (name === "edge") {
        currentEdge = null;
      }
      continue;
    }
    const attrs = parseAttrs(rawAttrs);
    const isSelfClosing = selfClosing === "/";

    switch (name) {
      case "location": {
        netOffset = null;
        const offsetRaw = attrs["netOffset"];
        if (offsetRaw !== undefined && offsetRaw !== "") {
          const parts = offsetRaw.split(",");
          const dx = Number(parts[0]);
          const dy = Number(parts[1]);
          netOffset = { dx: Number.isFinite(dx) ? dx : 0, dy: Number.isFinite(dy) ? dy : 0 };
        }
        const proj = attrs["projParameter"] ?? "!";
        geoReferenced = proj !== "!" && proj !== "";
        break;
      }
      case "junction": {
        const id = attrs["id"] ?? "";
        // Internal junctions (":I1_16_0") are part of intersection internals.
        if (id.startsWith(":") || id === "") break;
        junctions.push({
          id,
          kind: attrs["type"] ?? "dead_end",
          x: Number(attrs["x"] ?? 0),
          y: Number(attrs["y"] ?? 0),
          incLanes: (attrs["incLanes"] ?? "").split(/\s+/).filter((s) => s !== ""),
        });
        break;
      }
      case "edge": {
        const id = attrs["id"] ?? "";
        const functionAttr = attrs["function"] ?? "";
        // Internal edges (":I1_0") and anything without junctions are skipped.
        currentEdge =
          !id.startsWith(":") && id !== "" && attrs["from"] !== undefined && attrs["to"] !== undefined
            ? { id, fromJunction: attrs["from"]!, toJunction: attrs["to"]!, lanes: [] }
            : null;
        if (currentEdge !== null && functionAttr !== "" && functionAttr !== "normal") {
          currentEdge = null;
        }
        if (currentEdge !== null) {
          segments.push(currentEdge);
        }
        break;
      }
      case "lane": {
        // Lanes are children of the currently open edge element.
        if (currentEdge === null) break;
        currentEdge.lanes.push({
          id: attrs["id"] ?? "",
          index: Number(attrs["index"] ?? 0),
          speedMps: Number(attrs["speed"] ?? 0),
          lengthM: Number(attrs["length"] ?? 0),
          shape: parseShape(attrs["shape"] ?? ""),
        });
        break;
      }
      case "tlLogic": {
        const id = attrs["id"] ?? "";
        if (id === "") break;
        currentSignal = {
          id,
          programId: attrs["programID"] ?? "0",
          type: attrs["type"] ?? "static",
          phases: [],
        };
        signals.push(currentSignal);
        break;
      }
      case "phase": {
        if (currentSignal === null) break;
        currentSignal.phases.push({
          index: currentSignal.phases.length,
          durationS: Number(attrs["duration"] ?? 0),
          state: attrs["state"] ?? "",
        });
        break;
      }
      default:
        break;
    }

    if (name === "tlLogic" && isSelfClosing) {
      currentSignal = null;
    }
  }

  if (junctions.length === 0 || segments.length === 0) {
    throw new Error(
      `Network file ${netXmlPath} contains no junctions/segments; rebuild it with 'npm run build:network'.`,
    );
  }
  void netOffset;

  const roads = deriveRoads(segments);

  return { junctions, segments, roads, signals, geoReferenced };
}

/** Builds undirected roads: one road per unordered junction pair. */
function deriveRoads(segments: NetworkSegment[]): NetworkRoad[] {
  const byPair = new Map<string, NetworkRoad>();
  for (const segment of segments) {
    const sorted = [segment.fromJunction, segment.toJunction].sort();
    const a = sorted[0] ?? segment.fromJunction;
    const b = sorted[1] ?? segment.toJunction;
    const id = `${a}-${b}`;
    let road = byPair.get(id);
    if (road === undefined) {
      road = { id, fromJunction: a, toJunction: b, segmentIds: [] };
      byPair.set(id, road);
    }
    road.segmentIds.push(segment.id);
  }
  return [...byPair.values()];
}
